<a href="https://colab.research.google.com/github/AndresPautrat/DataMining/blob/main/SKLearn_Preprocesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn import preprocessing

In [ ]:
X_train=np.array([[1.,-1.,2.],[2.,0.,0.],[0.,1.,-1.]])

X_scaled=preprocessing.scale(X_train)

print(X_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [ ]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [ ]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [ ]:
scaler=preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
scalar.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

# Normalization

In [ ]:
X=[[1.,-1.,2.],[2.,0.,0.],[0.,1.,-1.]]
X_normalized=preprocessing.normalize(X,norm='l2')
print(X_normalized)

[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]


In [ ]:
normalizer= preprocessing.Normalizer().fit(X)
print(normalizer)

Normalizer(copy=True, norm='l2')


In [ ]:
normalizer.transform(X)

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imp= SimpleImputer(missing_values=np.nan,strategy='mean')
imp.fit([[1,2],[np.nan,3],[7,6]])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [ ]:
X=[[np.nan,2],[6,np.nan],[7,6]]
print(imp.transform(X))

[[4.         2.        ]
 [6.         3.66666667]
 [7.         6.        ]]


In [ ]:
import scipy.sparse as sp

In [ ]:
X=sp.csc_matrix([[1,2],[0,3],[7,6]])
print(X)

  (0, 0)	1
  (2, 0)	7
  (0, 1)	2
  (1, 1)	3
  (2, 1)	6


In [ ]:
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
imp.fit(X)

In [ ]:
X_test=sp.csc_matrix([[0,2],[6,0],[7,6]])
print(imp.transform(X_test))

  (1, 0)	6.0
  (2, 0)	7.0
  (0, 1)	2.0
  (2, 1)	6.0
